# Generated by Django 3.0.5 on 2020-04-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitemmodel',
            old_name='listmodel_id',
            new_name='listmodel',
        ),
    ]
