# Generated by Django 3.0.5 on 2020-04-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_item', '0002_auto_20200427_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitemmodel',
            old_name='expare_data',
            new_name='expire_date',
        ),
    ]
