# Generated by Django 3.0.5 on 2020-05-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_item', '0003_auto_20200430_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitemmodel',
            old_name='listmodel',
            new_name='list',
        ),
    ]
